In [4]:
from tensorflow.keras.models import load_model

In [5]:
model = load_model('model.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [7]:
import pickle
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('one_hot_encoder_geo.pkl', 'rb') as file:
    one_hot_encoder_geo = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [8]:
##[input] 
input_data = {
    'CreditScore': 800,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 70000,
    'NumOfProducts': 4,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 90000
}

In [12]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [26]:
encode_geo = one_hot_encoder_geo.transform([[input_data['Geography']]]).toarray()
encode_geo_df = pd.DataFrame(encode_geo, columns= one_hot_encoder_geo.get_feature_names_out(['Geography']))
encode_geo_df

d:\Project\Customer Churn Model\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [27]:
input_df = pd.DataFrame([input_data])
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          800    France   Male  ...          1               1            90000

[1 rows x 10 columns]

In [28]:
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          800    France       1  ...          1               1            90000

[1 rows x 10 columns]

In [29]:
input_df = pd.concat([input_df.drop("Geography", axis = 1), encode_geo_df],axis = 1)
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          800       1  ...                0.0              0.0

[1 rows x 12 columns]

In [30]:
input_scale = scaler.transform(input_df)

In [31]:
input_scale

array([[ 1.57627031,  0.90911166,  0.09477172, -0.69844549, -0.12912199,
         4.19859479,  0.63367318,  0.95214374, -0.15187203,  0.98019606,
        -0.57581067, -0.56349184]])

In [33]:
##Predict churn
prediction = model.predict(input_scale)
prediction_probability = prediction[0][0]
prediction_probability

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

np.float32(0.9980344)

In [ ]:
if prediction_probability > 0.5 : 
    print("Customer will likely churn")
else:
    print("Customer will likely not churn")

Customer will likely churn